# Copyright The IETF Trust 2026, All Rights Reserved
#
# Runs guides app, database, and a mailpit. Uses production mode.
#
# Known issues:
#  - At first start, the app service initializes faster than pgdb can start up and
#    create its empty database. The `restart: unless-stopped` on the app service is a
#    workaround. After a few restarts, pgdb is ready and app can then start up properly.
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgdb
    ports:
      - "8002:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ADMINS: "admin@example.org"
      ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://localhost:8002"
      DB_HOST: "pgdb"
      DB_NAME: "guides"
      DB_PASS: "abcd1234"
      DB_PORT: "5432"
      DB_USER: "guides"
      DEFAULT_FROM_EMAIL: "lead@guides.example.org"
      EMAIL_HOST: "mailpit"
      EMAIL_PORT: "1025"
      HASHSALT: "wxyz0"
      SECRET_KEY: "abcdef1234567890abcdef1234567890abcdef1234567890"
    restart: unless-stopped

  pgdb:
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: guides
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: guides

  mailpit:
    image: axllent/mailpit:v1.27
    environment:
      MP_DISABLE_VERSION_CHECK: true
      MP_LABEL: GuidesMail
    ports:
      - "8026:8025"

volumes:
  postgres-data: