# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('affiliation', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64, verbose_name='Country of residence')),
                ('ietf_years', models.CharField(choices=[('LESSTHANFIVE', 'Less than 5 years'), ('FIVETOTEN', '5 to 10 years'), ('MORETHANTEN', 'More than 10 years')], default='LESSTHANFIVE', max_length=32, verbose_name='How long have you been participating in the IETF?')),
                ('multiple_guided', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=32, verbose_name='Are you willing to work with more than one program participant?')),
                ('give_intro', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=32, verbose_name='Are you willing to give a general introduction of the IETF to a newcomer program participant?')),
                ('arrival_date', models.DateField(verbose_name='What date are you arriving at then next IETF meeting?')),
                ('additional_info', models.TextField(verbose_name='Is there anything else we should know?')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('affiliation', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64, verbose_name='Country of residence')),
                ('attend', models.CharField(choices=[('None', 'This is my first IETF meeting'), ('One', 'This is my second IETF meeting'), ('Few', 'I have been to two, three, or four IETF meetings')], default='None', max_length=32, verbose_name='IETF attendance')),
                ('topics', models.TextField(verbose_name='What technical topics brought you to the IETF?')),
                ('areas', models.CharField(help_text="ART, INT, OPS, RTG, SEC, TSG, I don't know yet", max_length=64, verbose_name='What IETF area(s) most interest you')),
                ('groups', models.CharField(help_text='see https://wwww.ietf.org/how/wgs', max_length=256, verbose_name='Which working groups are you most interested in?')),
                ('gender_pref', models.CharField(choices=[('NoPref', "I don't have a preference"), ('Male', 'I would prefer to work with a male guide'), ('Female', 'I would prefer to work with a female guide')], default='NoPref', max_length=32, verbose_name='Guide gender preference')),
                ('additional_info', models.TextField(verbose_name='Is there anything else you would like to share with us?')),
                ('language', models.ForeignKey(default=1, max_length=32, on_delete=django.db.models.deletion.CASCADE, to='guides.Language', verbose_name='Preferred conversational language')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.Participant'),
        ),
        migrations.AddField(
            model_name='guide',
            name='language',
            field=models.ManyToManyField(max_length=32, to='guides.Language', verbose_name='What languages can you communicate in fluently?'),
        ),
    ]
