# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 18:37
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    Language = apps.get_model('guides','Language')
    Language.objects.create(language='English')
    Language.objects.create(language='Cantonese')
    Language.objects.create(language='Mandarin')
    Language.objects.create(language='Hindi')
    Language.objects.create(language='German')
    Language.objects.create(language='French')
    Language.objects.create(language='Spanish')
    Language.objects.create(language='Japanese')
    Language.objects.create(language='Other')

def reverse(apps, schema_editor):
    Language = apps.get_model('guides','Language')
    Language.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward,reverse)
    ]
