# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_add_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='gender',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Is there anything else we should know?'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='arrival_date',
            field=models.CharField(max_length=64, verbose_name='What date are you arriving at then next IETF meeting (MM/DD/YYYY)?'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='give_intro',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', help_text='<em>(Sometimes it is not possible to exactly match guides with participants and their preferred technical areas)</em>', max_length=32, verbose_name='Are you willing to give a general introduction of the IETF to a newcomer program participant?'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Is there anything else you would like to share with us?'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='areas',
            field=models.CharField(help_text='<p>IETF Areas include:</p>\n<ul>\n<li>ART: Applications and Real-Time</li>\n<li>INT: Internet</li>\n<li>OPS: Operations and Management</li>\n<li>RTG: Routing</li>\n<li>SEC: Security</li>\n<li>TSG: Transport</li>\n<li>UNKNOWN: I don\'t know yet</li>\n</ul><p>Further information <a href="https://www.ietf.org/topics/areas/"> is also avaliable about IETF areas</a>', max_length=64, verbose_name='What IETF area(s) most interest you'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='attend',
            field=models.CharField(choices=[('None', 'This is my first IETF meeting'), ('One', 'This is my second IETF meeting'), ('Two', 'This is my third IETF meeting'), ('Three', 'This is my fourth IETF meeting')], default='None', max_length=32, verbose_name='Number of IETFs attended'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='groups',
            field=models.CharField(help_text='see <a href="https://wwww.ietf.org/how/wgs">https://wwww.ietf.org/how/wgs</a>', max_length=256, verbose_name='Which working groups are you most interested in?'),
        ),
    ]
