# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_allow_gender_to_be_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='gender',
            field=models.CharField(default='', max_length=32, verbose_name='Gender'),
        ),
    ]
