# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_disallow_null_on_gender__default_to_empty_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Gender'),
        ),
    ]
