# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_add_areas_and_groups_to_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='short',
            field=models.CharField(default='', max_length=12),
        ),
    ]
