# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 21:25
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    Area = apps.get_model('guides','Area')
    for (area,short) in [
        ('ART: Applications and Real-Time', 'art'),
        ('INT: Internet', 'int'),
        ('OPS: Operations and Management', 'ops'),
        ('RTG: Routing', 'rtg'),
        ('SEC: Security', 'sec'),
        ('TSG: Transport', 'tsv'),
        ("UNKNOWN: I don't know yet", 'unknown')
    ]:
        Area.objects.filter(area=area).update(short=short)

    Area.objects.filter(area__startswith='TSG').update(area = "TSV: Transport")

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0009_add_short_name_to_area'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
