# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0011_fix_typo_in_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='keep_for_nexttime',
            field=models.BooleanField(default=False, verbose_name='Should we keep your registration data around for future participation in the guides program?'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='arrival_date',
            field=models.CharField(max_length=64, verbose_name='What date are you arriving at then next IETF meeting (YYYY/MM/DD)?'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='groups',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Which working groups are you most able to help people with?'),
        ),
    ]
