# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0012_auto_20190304_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='arrival_date',
            field=models.CharField(max_length=64, verbose_name='What date are you arriving at the next IETF meeting (YYYY/MM/DD)?'),
        ),
    ]
