# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0013_auto_20190307_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='accept_remote',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=32, verbose_name='Are you willing to guide remote participants?'),
        ),
        migrations.AddField(
            model_name='participant',
            name='remote',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='NO', max_length=32, verbose_name='Will you be attending remotely?'),
        ),
    ]
