# Generated by Django 5.0.2 on 2024-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0019_alter_guide_remote"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Administrative Only"),
        ),
        migrations.AddField(
            model_name="participant",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Administrative Only"),
        ),
    ]
