# Define JSON log format - must be loaded before config that references it
log_format  ietfjson  escape=json
  '{'
    '"asctime":"$time_iso8601",'
    '"remote_ip":"$remote_addr",'
    '"request":"$request",'
    '"host":"$host",'
    '"path":"$request_uri",'
    '"method":"$request_method",'
    '"status":"$status",'
    '"len_bytes":"$body_bytes_sent",'
    '"duration_s":"$request_time",'
    '"referer":"$http_referer",'
    '"user_agent":"$http_user_agent",'
    '"x_forwarded_for":"$http_x_forwarded_for",'
    '"x_forwarded_proto":"$http_x_forwarded_proto",'
    '"cf_connecting_ip":"$http_cf_connecting_ip",'
    '"cf_connecting_ipv6":"$http_cf_connecting_ipv6",'
    '"cf_ray":"$http_cf_ray"'
  '}';
